export type Category =
  | 'Internship'
  | 'Hackathon'
  | 'Scholarship'
  | 'Competition'
  | 'Course'
  | 'Certification'
  | 'Workshop'
  | 'Fellowship'

export type Mode = 'Remote' | 'Hybrid' | 'On-site'

export const categories: Category[] = [
  'Internship',
  'Hackathon',
  'Scholarship',
  'Competition',
  'Course',
  'Certification',
  'Workshop',
  'Fellowship',
]

export const modes: Array<Mode | 'Any'> = ['Remote', 'Hybrid', 'On-site', 'Any']

export interface Opportunity {
  id: string
  title: string
  organization: string
  category: Category
  description: string
  location: string
  mode: Mode
  deadline: string
  skills: string[]
  eligibility: string
  education: string[]
  experience: string
  benefits: string[]
  tags: string[]
  url: string
  featured?: boolean
}

export interface Profile {
  name: string
  education: string
  stream: string
  location: string
  skills: string[]
  interests: string[]
  categories: Category[]
  experience: string
  mode: Mode | 'Any'
}

export const blankProfile: Profile = {
  name: '',
  education: '',
  stream: '',
  location: '',
  skills: [],
  interests: [],
  categories: [],
  experience: '',
  mode: 'Any',
}

export const demoProfile: Profile = {
  name: 'Aarav Sharma',
  education: 'Undergraduate',
  stream: 'Computer Science',
  location: 'Pune, Maharashtra',
  skills: ['Python', 'JavaScript', 'Git', 'UI/UX'],
  interests: ['AI', 'Startups', 'Technology'],
  categories: ['Internship', 'Hackathon', 'Course'],
  experience: 'Beginner',
  mode: 'Remote',
}

// Seed content is intentionally labeled as demo data in the UI. Dates are
// fixed for a stable hackathon demo and the matching engine stays deterministic.
export const opportunities: Opportunity[] = [
  {
    id: 'op-01',
    title: 'Applied AI Product Internship',
    organization: 'Northstar Labs',
    category: 'Internship',
    description: 'Ship small, useful AI features with a product engineering team working on tools for modern knowledge workers.',
    location: 'Bengaluru, India',
    mode: 'Hybrid',
    deadline: '2026-10-02',
    skills: ['Python', 'Machine Learning', 'Git', 'APIs'],
    eligibility: 'Open to students graduating in 2027 or later.',
    education: ['Undergraduate', 'Postgraduate'],
    experience: 'Beginner-friendly',
    benefits: ['Mentorship from product engineers', 'Certificate', 'Potential full-time interview'],
    tags: ['AI', 'Product', 'Startups'],
    url: 'https://example.com/northstar-ai-internship',
    featured: true,
  },
  {
    id: 'op-02',
    title: 'Build for Bharat Hackathon',
    organization: 'CivicStack Community',
    category: 'Hackathon',
    description: 'A 48-hour build sprint for practical technology that makes everyday services more accessible across India.',
    location: 'Online',
    mode: 'Remote',
    deadline: '2026-09-29',
    skills: ['JavaScript', 'React', 'UI/UX', 'Git'],
    eligibility: 'Students and early-career builders, solo or in teams of up to four.',
    education: ['High School', 'Undergraduate', 'Postgraduate'],
    experience: 'Any level',
    benefits: ['₹1,00,000 prize pool', 'Expert feedback', 'Demo day showcase'],
    tags: ['Technology', 'Startups', 'Social Impact'],
    url: 'https://example.com/build-for-bharat',
    featured: true,
  },
  {
    id: 'op-03',
    title: 'Future Innovators Scholarship',
    organization: 'BrightMinds Foundation',
    category: 'Scholarship',
    description: 'Need-aware support for students building a track record in technology, design, science, or community impact.',
    location: 'India',
    mode: 'Remote',
    deadline: '2026-10-06',
    skills: ['Communication', 'Research'],
    eligibility: 'Students with a strong academic record and a documented project or community initiative.',
    education: ['Undergraduate', 'Postgraduate'],
    experience: 'Any level',
    benefits: ['Up to ₹75,000 education grant', 'Peer community', 'Annual mentor circle'],
    tags: ['Scholarship', 'AI', 'Technology'],
    url: 'https://example.com/future-innovators',
  },
  {
    id: 'op-04',
    title: 'Open Source Sprint: Climate Tools',
    organization: 'GreenCode Network',
    category: 'Competition',
    description: 'Contribute to open-source data tools that help communities understand and respond to local climate risks.',
    location: 'Online',
    mode: 'Remote',
    deadline: '2026-10-04',
    skills: ['Python', 'JavaScript', 'Git', 'Data Analysis'],
    eligibility: 'Open to students and developers at all levels. Prior open-source work is welcome, not required.',
    education: ['High School', 'Undergraduate', 'Postgraduate'],
    experience: 'Any level',
    benefits: ['Portfolio-ready contribution', 'Community recognition', 'Maintainer feedback'],
    tags: ['Technology', 'Research', 'Social Impact'],
    url: 'https://example.com/greencode-sprint',
  },
  {
    id: 'op-05',
    title: 'Machine Learning Foundations',
    organization: 'LearnLab Academy',
    category: 'Course',
    description: 'A guided six-week course covering the practical ML workflow from data cleaning through model evaluation.',
    location: 'Online',
    mode: 'Remote',
    deadline: '2026-10-12',
    skills: ['Python', 'Machine Learning', 'Data Analysis'],
    eligibility: 'Open to learners comfortable with basic programming and high-school mathematics.',
    education: ['Undergraduate', 'Postgraduate', 'High School'],
    experience: 'Beginner-friendly',
    benefits: ['Project-based curriculum', 'Peer reviews', 'Completion certificate'],
    tags: ['AI', 'Technology', 'Learning'],
    url: 'https://example.com/learnlab-ml',
    featured: true,
  },
  {
    id: 'op-06',
    title: 'Google Cloud Digital Leader Prep',
    organization: 'CloudBridge Learning',
    category: 'Certification',
    description: 'Self-paced preparation cohort for learners who want a business and technology foundation in cloud computing.',
    location: 'Online',
    mode: 'Remote',
    deadline: '2026-10-19',
    skills: ['Cloud', 'Communication', 'Technology'],
    eligibility: 'No prior cloud certification required.',
    education: ['High School', 'Undergraduate', 'Postgraduate'],
    experience: 'Any level',
    benefits: ['Practice assessments', 'Study group', 'Exam readiness plan'],
    tags: ['Technology', 'Certification', 'Career'],
    url: 'https://example.com/cloudbridge-leader',
  },
  {
    id: 'op-07',
    title: 'Designing AI Products Workshop',
    organization: 'Product People India',
    category: 'Workshop',
    description: 'A hands-on workshop about turning a fuzzy AI idea into a clear, testable product experience.',
    location: 'Mumbai, India',
    mode: 'On-site',
    deadline: '2026-10-01',
    skills: ['UI/UX', 'Research', 'Communication'],
    eligibility: 'Students, designers, and builders interested in responsible AI products.',
    education: ['Undergraduate', 'Postgraduate'],
    experience: 'Any level',
    benefits: ['Live teardown', 'Workshop workbook', 'Community access'],
    tags: ['AI', 'UI/UX', 'Product'],
    url: 'https://example.com/designing-ai-products',
  },
  {
    id: 'op-08',
    title: 'South Asia Tech Fellowship',
    organization: 'Open Futures Collective',
    category: 'Fellowship',
    description: 'A part-time fellowship for emerging technologists exploring how digital tools can widen access to opportunity.',
    location: 'Online',
    mode: 'Hybrid',
    deadline: '2026-10-15',
    skills: ['Research', 'Communication', 'JavaScript'],
    eligibility: 'Students or recent graduates with a demonstrated interest in technology and public impact.',
    education: ['Undergraduate', 'Postgraduate'],
    experience: 'Beginner-friendly',
    benefits: ['₹30,000 project grant', 'Mentor network', 'Cohort showcase'],
    tags: ['Technology', 'Startups', 'Social Impact'],
    url: 'https://example.com/open-futures-fellowship',
  },
  {
    id: 'op-09',
    title: 'Frontend Engineering Intern',
    organization: 'Pixel & Logic',
    category: 'Internship',
    description: 'Join a small product team to build fast, accessible interfaces for independent businesses.',
    location: 'Pune, Maharashtra',
    mode: 'Hybrid',
    deadline: '2026-10-08',
    skills: ['JavaScript', 'React', 'UI/UX', 'Git'],
    eligibility: 'Currently enrolled in a degree program or graduated within the last year.',
    education: ['Undergraduate', 'Postgraduate'],
    experience: 'Beginner-friendly',
    benefits: ['Paid internship', 'Weekly design critiques', 'Flexible hours'],
    tags: ['Startups', 'Technology', 'UI/UX'],
    url: 'https://example.com/pixel-logic-internship',
    featured: true,
  },
  {
    id: 'op-10',
    title: 'Women in Tech Build Challenge',
    organization: 'HerCode Alliance',
    category: 'Competition',
    description: 'A friendly build challenge celebrating solutions created by women and gender-diverse students.',
    location: 'Online',
    mode: 'Remote',
    deadline: '2026-10-10',
    skills: ['JavaScript', 'Python', 'UI/UX'],
    eligibility: 'Women and gender-diverse students in India, participating solo or in teams.',
    education: ['High School', 'Undergraduate', 'Postgraduate'],
    experience: 'Any level',
    benefits: ['Mentor office hours', 'Prizes and grants', 'Hiring showcase'],
    tags: ['Technology', 'Startups', 'UI/UX'],
    url: 'https://example.com/hercode-challenge',
  },
  {
    id: 'op-11',
    title: 'Product Analytics with SQL',
    organization: 'Metric School',
    category: 'Course',
    description: 'Learn to turn product questions into useful metrics, queries, and decisions through practical case studies.',
    location: 'Online',
    mode: 'Remote',
    deadline: '2026-11-01',
    skills: ['SQL', 'Data Analysis', 'Communication'],
    eligibility: 'Open to students with basic spreadsheet or programming experience.',
    education: ['Undergraduate', 'Postgraduate', 'High School'],
    experience: 'Beginner-friendly',
    benefits: ['Case study portfolio', 'Instructor feedback', 'Alumni Slack'],
    tags: ['Technology', 'Career', 'Startups'],
    url: 'https://example.com/metric-school-sql',
  },
  {
    id: 'op-12',
    title: 'National Student Cyber League',
    organization: 'SecurePath India',
    category: 'Competition',
    description: 'Solve practical security challenges across web, cloud, and digital forensics in a beginner-friendly league.',
    location: 'Online',
    mode: 'Remote',
    deadline: '2026-10-22',
    skills: ['Cybersecurity', 'Python', 'Cloud'],
    eligibility: 'Students enrolled in an Indian school, college, or university.',
    education: ['High School', 'Undergraduate', 'Postgraduate'],
    experience: 'Any level',
    benefits: ['Ranked leaderboard', 'Security mentor AMA', 'Interview fast-track'],
    tags: ['Technology', 'Career', 'Competition'],
    url: 'https://example.com/securepath-league',
  },
  {
    id: 'op-13',
    title: 'Social Impact Data Fellowship',
    organization: 'Civic Signals',
    category: 'Fellowship',
    description: 'Work with nonprofit partners to turn messy public data into clear stories and decisions.',
    location: 'Delhi, India',
    mode: 'Hybrid',
    deadline: '2026-10-28',
    skills: ['Data Analysis', 'Python', 'Research'],
    eligibility: 'Students or recent graduates with an interest in evidence-led social change.',
    education: ['Undergraduate', 'Postgraduate'],
    experience: 'Beginner-friendly',
    benefits: ['Stipend', 'Public portfolio project', 'Research mentorship'],
    tags: ['Research', 'Social Impact', 'Technology'],
    url: 'https://example.com/civic-signals-fellowship',
  },
  {
    id: 'op-14',
    title: 'No-Code to AI Workshop Series',
    organization: 'MakerHouse',
    category: 'Workshop',
    description: 'A three-session live series for turning a problem from your campus or community into a working AI prototype.',
    location: 'Online',
    mode: 'Remote',
    deadline: '2026-10-03',
    skills: ['UI/UX', 'Communication', 'AI'],
    eligibility: 'Open to students, regardless of technical background.',
    education: ['High School', 'Undergraduate', 'Postgraduate'],
    experience: 'Any level',
    benefits: ['Prototype feedback', 'Templates and tools', 'Demo day'],
    tags: ['AI', 'Startups', 'Learning'],
    url: 'https://example.com/makerhouse-ai',
  },
  {
    id: 'op-15',
    title: 'Women in STEM Access Grant',
    organization: 'FutureFoundry',
    category: 'Scholarship',
    description: 'A small education grant for women pursuing a technical degree and building projects outside the classroom.',
    location: 'India',
    mode: 'Remote',
    deadline: '2026-11-05',
    skills: ['Communication', 'Research'],
    eligibility: 'Women pursuing an undergraduate or postgraduate STEM degree in India.',
    education: ['Undergraduate', 'Postgraduate'],
    experience: 'Any level',
    benefits: ['Up to ₹50,000 grant', 'Mentor matching', 'Community meetups'],
    tags: ['Scholarship', 'Technology', 'Career'],
    url: 'https://example.com/futurefoundry-grant',
  },
  {
    id: 'op-16',
    title: 'Cloud Native Campus Hack',
    organization: 'KubeCampus',
    category: 'Hackathon',
    description: 'Build a deployable service with containers, APIs, or event-driven architecture alongside cloud mentors.',
    location: 'Bengaluru, India',
    mode: 'Hybrid',
    deadline: '2026-10-17',
    skills: ['JavaScript', 'Cloud', 'Git', 'APIs'],
    eligibility: 'College students and recent graduates, teams of two to five.',
    education: ['Undergraduate', 'Postgraduate'],
    experience: 'Any level',
    benefits: ['Cloud credits', 'Mentor sessions', 'Hardware prizes'],
    tags: ['Technology', 'Startups', 'Cloud'],
    url: 'https://example.com/kubecampus',
  },
  {
    id: 'op-17',
    title: 'Responsible AI Certificate',
    organization: 'Ethos Institute',
    category: 'Certification',
    description: 'A short certificate program covering fairness, transparency, privacy, and practical AI governance.',
    location: 'Online',
    mode: 'Remote',
    deadline: '2026-10-31',
    skills: ['AI', 'Research', 'Communication'],
    eligibility: 'Open to students, educators, and early-career professionals.',
    education: ['Undergraduate', 'Postgraduate', 'High School'],
    experience: 'Any level',
    benefits: ['Verified certificate', 'Case library', 'Expert roundtable'],
    tags: ['AI', 'Research', 'Technology'],
    url: 'https://example.com/ethos-responsible-ai',
  },
  {
    id: 'op-18',
    title: 'Startup Studio Product Intern',
    organization: 'Launchpad Ventures',
    category: 'Internship',
    description: 'Explore customer discovery, experiments, and early product delivery inside a venture studio.',
    location: 'Mumbai, India',
    mode: 'On-site',
    deadline: '2026-10-13',
    skills: ['UI/UX', 'Research', 'Communication', 'JavaScript'],
    eligibility: 'Students with a strong interest in startups and product building.',
    education: ['Undergraduate', 'Postgraduate'],
    experience: 'Beginner-friendly',
    benefits: ['Stipend', 'Founder exposure', 'Product portfolio'],
    tags: ['Startups', 'Product', 'Technology'],
    url: 'https://example.com/launchpad-product',
  },
  {
    id: 'op-19',
    title: 'Open Web Student Fellowship',
    organization: 'Web Standards Forum',
    category: 'Fellowship',
    description: 'Learn how the open web evolves while contributing research, documentation, or community tooling.',
    location: 'Online',
    mode: 'Remote',
    deadline: '2026-11-12',
    skills: ['JavaScript', 'Research', 'Communication', 'Git'],
    eligibility: 'Students passionate about the web platform, accessibility, or open collaboration.',
    education: ['Undergraduate', 'Postgraduate'],
    experience: 'Any level',
    benefits: ['Monthly stipend', 'Standards mentorship', 'Conference opportunity'],
    tags: ['Technology', 'UI/UX', 'Research'],
    url: 'https://example.com/open-web-fellowship',
  },
  {
    id: 'op-20',
    title: 'Global Code Jam Student Edition',
    organization: 'CodeLeague',
    category: 'Competition',
    description: 'A timed algorithm and product-thinking competition designed for students who want a sharp portfolio signal.',
    location: 'Online',
    mode: 'Remote',
    deadline: '2026-10-07',
    skills: ['Python', 'JavaScript', 'Algorithms'],
    eligibility: 'Students enrolled in any recognized school or university.',
    education: ['High School', 'Undergraduate', 'Postgraduate'],
    experience: 'Any level',
    benefits: ['Global ranking', 'Problem-solving report', 'Recruiter visibility'],
    tags: ['Technology', 'Career', 'Competition'],
    url: 'https://example.com/codeleague-jam',
  },
  {
    id: 'op-21',
    title: 'UX Research for Emerging Markets',
    organization: 'FieldNotes Studio',
    category: 'Course',
    description: 'Practice interview design, synthesis, and inclusive research through realistic product briefs.',
    location: 'Online',
    mode: 'Remote',
    deadline: '2026-10-25',
    skills: ['UI/UX', 'Research', 'Communication'],
    eligibility: 'Open to students exploring design, product, or social innovation.',
    education: ['Undergraduate', 'Postgraduate', 'High School'],
    experience: 'Beginner-friendly',
    benefits: ['Research toolkit', 'Critique sessions', 'Case-study portfolio'],
    tags: ['UI/UX', 'Research', 'Startups'],
    url: 'https://example.com/fieldnotes-ux',
  },
  {
    id: 'op-22',
    title: 'Girls Who Build India Hacknight',
    organization: 'CodeSakhi',
    category: 'Hackathon',
    description: 'An inclusive evening hacknight to build playful, practical digital solutions with a supportive peer community.',
    location: 'Pune, Maharashtra',
    mode: 'On-site',
    deadline: '2026-09-30',
    skills: ['JavaScript', 'UI/UX', 'Git'],
    eligibility: 'Women and gender-diverse students based in or near Pune.',
    education: ['High School', 'Undergraduate', 'Postgraduate'],
    experience: 'Any level',
    benefits: ['Community dinner', 'Mentor desk', 'Prizes and swag'],
    tags: ['Technology', 'Startups', 'UI/UX'],
    url: 'https://example.com/codesakhi-hacknight',
  },
  {
    id: 'op-23',
    title: 'Data for Public Good Internship',
    organization: 'Impact Metrics Lab',
    category: 'Internship',
    description: 'Support nonprofit partners with dashboards, analysis, and clear communication of what the data means.',
    location: 'Online',
    mode: 'Remote',
    deadline: '2026-10-20',
    skills: ['Python', 'Data Analysis', 'Communication'],
    eligibility: 'Students with curiosity about data, public systems, or social impact.',
    education: ['Undergraduate', 'Postgraduate'],
    experience: 'Beginner-friendly',
    benefits: ['Stipend', 'Portfolio case study', 'Weekly mentorship'],
    tags: ['Research', 'Social Impact', 'Technology'],
    url: 'https://example.com/impact-metrics',
  },
  {
    id: 'op-24',
    title: 'Founders 101 Live Lab',
    organization: 'Campus Founders Club',
    category: 'Workshop',
    description: 'A practical evening lab on problem selection, customer conversations, and shipping the first version.',
    location: 'Bengaluru, India',
    mode: 'Hybrid',
    deadline: '2026-10-09',
    skills: ['Communication', 'Research', 'UI/UX'],
    eligibility: 'Students and recent graduates exploring entrepreneurship.',
    education: ['Undergraduate', 'Postgraduate'],
    experience: 'Any level',
    benefits: ['Founder playbook', 'Peer feedback', 'Pitch practice'],
    tags: ['Startups', 'Product', 'Learning'],
    url: 'https://example.com/campus-founders',
  },
]